import Head from "next/head";
import NavBar from "../components/navbar/NavBar";
import Overview from "../components/Overview";
import About from "../components/About";
import Experiences from "../components/experience/Experiences";
import Projects from "../components/projects/Projects";
import Contact from "../components/contact/Contact";
import Footer from "../components/Footer";
import { Box, VStack } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bennett A Desmond</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Bennett_Logo-01.svg" />
      </Head>
      <Box marginX="10%">
        <NavBar></NavBar>
        <VStack spacing={20}>
          <Overview></Overview>
          <About></About>
          <Experiences></Experiences>
          <Projects></Projects>
          <Contact></Contact>
          <Footer></Footer>
        </VStack>
      </Box>
    </>
  );
}
